/**
 * Types:
 * --------------------------------------
 *   0 full class
 *   1 single move / snippet
 *   2 aerials
 *   3 routine
 *   4 google drive
 *
 */

const VIDEOS =
[
  {id: 1,file:"cross-overs-2017/lesson1.mp4",type: 1,tags:["charleston", "airplane"],desc:"Switching sides in airplane tandem charleston",origin:"Cross Overs 2017",teachers: ["Ari", "Simon"]},
  {id: 2,file:"cross-overs-2017/lesson2.mp4",type: 1,tags:["tandem", "charleston", "intro"],desc:"Variation to get into tandem charleston, follow runs into her arm",origin:"Cross Overs 2017",teachers: ["Ari", "Simon"]},
  {id: 3,file:"cross-overs-2017/lesson3.mp4",type: 1,tags:["swingout", "backwards", "follow"],desc:"Follow goes straight then moves backwards",origin:"Cross Overs 2017",teachers: ["Ari", "Simon"]},
  {id: 4,file:"cross-overs-2017/lesson4.mp4",type: 1,tags:["swingout", "footwork", "variation"],desc:"Fun swingout footwork variation",origin:"Cross Overs 2017",teachers: ["Ari", "Simon"]},
  {id: 5,file:"cross-overs-2017/lesson5.mp4",type: 1,tags:["change of place", "lock step", "footwork"],desc:"Break with lock step",origin:"Cross Overs 2017",teachers: ["Ari", "Simon"]},
  {id: 6,file:"cross-overs-2017/lesson6.mp4",type: 1,tags:["tandem", "charleston", "lock step"],desc:"Tandem into windshield wiper lockstep to hand to hand",origin:"Cross Overs 2017",teachers: ["Ari", "Simon"]},
  {id: 7,file:"cross-overs-2017/lesson7.mp4",type: 1,tags:["tuck turn", "airplane"],desc:"Tuck turn into airplane",origin:"Cross Overs 2017",teachers: ["Ari", "Simon"]},
  {id: 8,file:"2012_BNJ.mp4",type: 1,tags:["tuck turn", "break", "hand to hand"],desc:"Tuck turn with kicks into break to hand to hand",origin:"BNJ 2012",url: "https://www.youtube.com/watch?v=gisafTmbVd8",teachers:[]},
  {id: 9,file:"cross-overs-2017/lesson8.mp4",type: 1,tags:["swingout", "variation", "inside turn"],desc:"Variation on swingout with inside turn",origin:"Cross Overs 2017",teachers: ["Ari", "Simon"]},
  {id: 10,file:"shorty-georges-2017/lesson7.mp4",type: 0,tags:[],desc:"",origin:"Shorty Georges 2017",teachers:["Bram", "Maaike"]},
  {id: 11,file:"shorty-georges-2017/lesson1.mp4",type: 0,tags:[],desc:"",origin:"Shorty Georges 2017",teachers:["Bram", "Maaike"]},
  {id: 12,file:"shorty-georges-2017/lesson2.mp4",type: 0,tags:[],desc:"",origin:"Shorty Georges 2017",teachers:["Bram", "Maaike"]},
  {id: 13,file:"shorty-georges-2017/lesson3.mp4",type: 0,tags:[],desc:"",origin:"Shorty Georges 2017",teachers:["Bram", "Maaike"]},
  {id: 14,file:"shorty-georges-2017/lesson4.mp4",type: 0,tags:["airplane", "tandem", "handtohand"],desc:"",origin:"Shorty Georges 2017",teachers:["Bram", "Maaike"]},
  {id: 15,file:"shorty-georges-2017/lesson5.mp4",type: 0,tags:["chase", "tandem"],desc:"",origin:"Shorty Georges 2017",teachers:["Bram", "Maaike"]},
  {id: 16,file:"shorty-georges-2017/lesson6.mp4",type: 0,tags:[],desc:"",origin:"Shorty Georges 2017",teachers:["Bram", "Maaike"]},
  {id: 17,file:"lindyshock-2017/peterkatja.mov",type: 0,tags:[],desc:"",origin:"Lindy Shock 2017",teachers:["Peter", "Katja"]},
  {id: 18,file:"lindyshock-2017/gasalba.mov",type: 0,tags:[],desc:"",origin:"Lindy Shock 2017",teachers:["Gas", "Alba"]},
  {id: 19,file:"lindyshock-2017/stephanlee.mov",type: 0,tags:[],desc:"",origin:"Lindy Shock 2017",teachers:["Stephan", "Lee"]},
  {id: 20,file:"lindyshock-2017/alexeyvassia.mov",type: 0,tags:["swingout", "footwork"],desc:"",origin:"Lindy Shock 2017",teachers:["Alexey", "Vassia"]},
  {id: 21,file:"lindyshock-2017/camcat.mov",type: 0,tags:[],desc:"",origin:"Lindy Shock 2017",teachers:["Cam", "Cat"]},
  {id: 22,file:"2015_CJB_2.mp4",type: 1,tags:["airplane", "tandem", "charleston"],desc:"Charleston tandem to side by side airplane",origin:"",url: "https://www.youtube.com/watch?v=8DwU6-M_FsY",teachers:[]},
  {id: 23,file:"aerials-2018/arisimon2.mp4",type: 2,tags:["aerials", "sweep", "around"],desc:"Sweep follow around into dip",origin:"Aerials 2018",teachers:["Ari", "Simon"]},
  {id: 24,file:"aerials-2018/arisimon1.mp4",type: 2,tags:["aerials", "lindy", "flip"],desc:"Lindy flip",origin:"Aerials 2018",teachers:["Ari", "Simon"]},
  {id: 25,file:"2011_UN_MAJA_1.mp4",type: 1,tags:["swingout", "basket"],desc:"Swingout into basket",origin:"",url: "https://www.youtube.com/watch?v=czv3olOrPOU",teachers:["Marcus Coker", "Janie Austin"]},
  {id: 26,file:"2018_SYCI_EVMI_1.mp4",type: 1,tags:["shoulder", "catch"],desc:"Shoulder catch",origin:"",url: "https://www.youtube.com/watch?v=6Lkt6TiIBG4",teachers:["Evita Arce", "Michael"]},
  {id: 27,file:"2015_UN_TOLA_1.mp4",type: 1,tags:["texastommy"],desc:"Texas Tommy from closed to closed position",origin:"",url: "https://www.youtube.com/watch?v=PKfiW23JxtM",teachers:["Todd Yannacone", "Laura Glaess"]},
  {id: 28,file:"2015_UN_TOLA_2.mp4",type: 1,tags:["texastommy"],desc:"Texas Tommy variations",origin:"",url: "https://www.youtube.com/watch?v=PKfiW23JxtM",teachers:["Todd Yannacone", "Laura Glaess"]},
  {id: 29,file:"bootcamp-2018/lesson6.mp4",type: 1,tags:["double", "swingout"],desc:"Double swingout variation",origin:"Crazy Legs Bootcamp 2018",teachers:["Ari", "Simon"]},
  {id: 30,file:"2011_UN_MAJA_2.mp4",type: 1,tags:["double", "basket"],desc:"Double basket",origin:"",url: "https://www.youtube.com/watch?v=czv3olOrPOU",teachers:["Marcus Coker", "Janie Austin"]},
  {id: 31,file:"2013_UN_NABR.mp4",type: 1,tags:["chase", "tandem", "charleston"],desc:"Basic chase into tandem",origin:"",url: "https://www.youtube.com/watch?v=lVQt-AYgL4g",teachers:[]},
  {id: 32,file:"2009_AEWO_KETI.mp4",type: 2,tags:["aerials", "lindy", "flip"],desc:"Lindy flip",origin:"",url: "https://www.youtube.com/watch?v=czv3olOrPOU",teachers:["Kenny", "Tiffany"]},
  {id: 33,file:"aerials-2018/arisimon3.mp4",type: 2,tags:["aerials", "frog", "jump", "swingout"],desc:"Frog jump swingout",origin:"Aerials 2018",teachers:["Ari", "Simon"]},
  {id: 34,file:"lindyshock-2017/janezpetra.mov",type: 0,tags:[],desc:"",origin:"Lindy Shock 2017",teachers:["Janez", "Petra"]},
  {id: 35,file:"bootcamp-2018/lesson1.mp4",type: 0,tags:[],desc:"",origin:"Crazy Legs Bootcamp 2018",teachers:["Ari", "Simon"]},
  {id: 36,file:"bootcamp-2018/lesson2.mp4",type: 0,tags:[],desc:"",origin:"Crazy Legs Bootcamp 2018",teachers:["Ari", "Simon"]},
  {id: 37,file:"bootcamp-2018/lesson3.mp4",type: 0,tags:[],desc:"",origin:"Crazy Legs Bootcamp 2018",teachers:["Ari", "Simon"]},
  {id: 38,file:"bootcamp-2018/lesson4.mp4",type: 0,tags:[],desc:"",origin:"Crazy Legs Bootcamp 2018",teachers:["Ari", "Simon"]},
  {id: 39,file:"bootcamp-2018/lesson5.mp4",type: 0,tags:[],desc:"",origin:"Crazy Legs Bootcamp 2018",teachers:["Ari", "Simon"]},
  {id: 40,file:"2015_CJB_1.mp4",type: 1,tags:["reverse", "basket", "jigwalk"],desc:"Reverse basket into jigwalk",origin:"Camp Jitterbug 2015",url: "https://www.youtube.com/watch?v=8DwU6-M_FsY",teachers:[]},
  {id: 41,file:"2014_SIS_KE_1.mp4",type: 1,tags:["tandem", "charleston", "yoyo", "turn"],desc:"Tandem yoyo with lead turn",origin:"",url: "https://www.youtube.com/watch?v=OqVcQak7eWQ",teachers:["Kenny"]},
  {id: 42,file:"shimmies-2019/arisimon1.mp4",type: 0,tags:["swingout", "tandem", "charleston", "hand to hand"],desc:"",origin:"Shimmies 2019",teachers:["Ari", "Simon"]},
  {id: 43,file:"shimmies-2019/arisimon2.mp4",type: 0,tags:[],desc:"",origin:"Shimmies 2019",teachers:["Ari", "Simon"]},
  {id: 44,file:"cross-overs-2018/lesson1.mp4",type: 0,tags:["swingout", "whip", "overrotated"],desc:"",origin:"Cross Overs NJ 2018",teachers:["Stoff", "Anja"]},
  {id: 45,file:"superdancers/arisimon1.mp4",type: 0,tags:[],desc:"",origin:"Superdancers",teachers:["Ari", "Simon"]},
  {id: 46,file:"shimmies-2019/sepcarla.mp4",type: 0,tags:["Swingout"],desc:"",origin:"Shimmies 2019",teachers:["Sep", "Carla"]},
  {id: 47,file:"2018_CSC_VIKA.mp4",type: 0,tags:["sailor", "kicks"],desc:"",origin:"Crazy Swing Camp 2018",teachers:["Vincenzo", "Katja"]},
  {id: 48,file:"2017_CSC.mp4",type: 0,tags:[],desc:"",origin:"Crazy Swing Camp 2017",teachers:[]},
  {id: 49,file:"2019_CSC_LERO.mp4",type: 0,tags:[],desc:"",origin:"Crazy Swing Camp 2019",teachers:["Leo", "Roser"]},
  {id: 50,file:"2019_CSC_HESO.mp4",type: 0,tags:[],desc:"",origin:"Crazy Swing Camp 2019",teachers:["Hector", "Sonja"]},
  {id: 51,file:"superdancers/arisimon2.mp4",type: 0,tags:[],desc:"",origin:"Superdancers",teachers:["Ari", "Simon"]},
  {id: 52,file:"superdancers/arisimon3.mp4",type: 0,tags:[],desc:"",origin:"Superdancers",teachers:["Ari", "Simon"]},
  {id: 53,file:"2018_CSC_SK.mp4",type: 0,tags:["flying", "charleston"],desc:"",origin:"Crazy Swing Camp 2018",teachers:["Skye"]},
  {id: 54,file:"lindyshock-2017/shortyira.mov",type: 0,tags:[],desc:"",origin:"Lindy Shock 2017",teachers:["Shorty", "Ira"]},
  {id: 55,file:"cross-overs-2017/lesson10.mp4",type: 0,tags:[],desc:"Class 03/10/2017",origin:"Cross Overs 2017",teachers: ["Ari", "Simon"]},
  {id: 56,file:"cross-overs-2017/lesson9.mp4",type: 0,tags:[],desc:"Class 10/10/2017",origin:"Cross Overs 2017",teachers: ["Ari", "Simon"]},
  {id: 57,file:"cross-overs-2018/lesson2.mp4",type: 0,tags:[],desc:"Class 13/11/2018",origin:"Cross Overs NJ 2018",teachers:["Stoff", "Anja"]},
  {id: 58,file:"cross-overs-2018/lesson3.mp4",type: 0,tags:[],desc:"Class 20/11/2018",origin:"Cross Overs NJ 2018",teachers:["Stoff", "Anja"]},
  {id: 59,file:"2018_CSC_GAAL.mp4",type: 0,tags:["swingout", "footwork", "variation"],desc:"",origin:"Crazy Swing Camp 2018",teachers:["Gas", "Alba"]},
  {id: 60,file:"2018_SYCI_EVMI_2.mp4",type: 1,tags:["shoulder", "catch"],desc:"Shoulder catch",origin:"",url: "https://www.youtube.com/watch?v=6Lkt6TiIBG4",teachers:["Evita Arce", "Michael"]},
  {id: 61,file:"2014_SIS_KE_2.mp4",type: 0,tags:["swginout", "cutoff"],desc:"Tandem yoyo with lead turn",origin:"",url: "https://www.youtube.com/watch?v=srUE_WlhhlA",teachers:["Kenny"]},
  {id: 62,file:"2015_CJB_3.mp4",type: 1,tags:["double", "basket"],desc:"Basket into basket with spin",origin:"Camp Jitterbug 2015",url: "https://www.youtube.com/watch?v=8DwU6-M_FsY",teachers:[]},
  {id: 63,file:"IG/20200517_IG_ARSI.mp4",type: 3,tags:["footwork"],desc:"Small fun routine",origin: "",url: "https://www.instagram.com/p/CASnt3DoDFu/",teachers:["Ari", "Simon"]},
  {id: 64,file:"herrang-2018/lesson1.mp4",type: 0,tags:[],desc:"",origin:"Herrang 2018",teachers:["Frederic", "Mimmi"]},
  {id: 65,file:"herrang-2018/lesson3.mp4",type: 0,tags:[],desc:"",origin:"Herrang 2018",teachers:["Skye", "Frida"]},
  {id: 66,file:"herrang-2018/lesson4.mp4",type: 0,tags:[],desc:"",origin:"Herrang 2018",teachers:["Skye", "Frida"]},
  {id: 67,file:"herrang-2018/lesson8.mp4",type: 0,tags:[],desc:"",origin:"Herrang 2018",teachers:["Lennart"]},
  {id: 68,file:"2019_RTSF_SOTA.mp4",type: 1,tags:[],desc:"",origin:"Rock That Swing Festival 2019",teachers:["Sondre", "Tanya"]},
  {id: 69,file: "crazylegs-weekend-2018/arisimon1.mp4",type: 0,tags:[],desc:"",origin:"Crazy Legs weekend 2018",teachers:["Ari", "Simon"]},
  {id: 70,file:"crazylegs-weekend-2018/arisimon2.mp4",type: 0,tags:[],desc:"",origin:"Crazy Legs weekend 2018",teachers:["Ari", "Simon"]},
  {id: 71,file:"2020_RTSF_1.mp4",type: 1,tags:[],desc:"",origin:"Rock That Swing Festival 2020",url: "https://www.youtube.com/watch?v=s4C8qwR3oj0",teachers:[]},
  {id: 72,file:"bootcamp-2020/arisimon1.mp4",type: 0,tags:[],desc:"Monday 17/08",origin:"Crazy Legs Bootcamp 2020",url: "",teachers:["Ari", "Simon"]},
  {id: 73,file:"bootcamp-2020/arisimon2.mp4",type: 0,tags:[],desc:"Tuesday 18/08",origin:"Crazy Legs Bootcamp 2020",url: "",teachers:["Ari", "Simon"]},
  {id: 74,file:"bootcamp-2020/arisimon3.mp4",type: 0,tags:[],desc:"Wednesday 19/08",origin:"Crazy Legs Bootcamp 2020",url: "",teachers:["Ari", "Simon"]},
  {id: 75,file:"bootcamp-2020/arisimon4.mp4",type: 0,tags:[],desc:"Thursday 20/08",origin:"Crazy Legs Bootcamp 2020",url: "",teachers:["Ari", "Simon"]},
  {id: 76,file:"bootcamp-2020/arisimon5.mp4",type: 0,tags:[],desc:"Saturday 22/08 mini bootcamp 1",origin:"Crazy Legs Bootcamp 2020",url: "",teachers:["Ari", "Simon"]},
  {id: 77,file:"bootcamp-2020/arisimon6.mp4",type: 0,tags:[],desc:"Saturday 22/08 mini bootcamp 2",origin:"Crazy Legs Bootcamp 2020",url: "",teachers:["Ari", "Simon"]},
  {id: 78,file:"bootcamp-2020/arisimon7.mp4",type: 0,tags:[],desc:"Saturday 22/08 mini bootcamp 3",origin:"Crazy Legs Bootcamp 2020",url: "",teachers:["Ari", "Simon"]},
  {id: 79,file:"2019_MLF_NIBA.mp4",type: 1,tags:["swingout"],desc:"",origin:"Mallorca Lindy Fest 2019",url: "https://www.youtube.com/watch?v=2q2OkfSXJa4",teachers:["Nils", "Bianca"]},
  {id: 80,file:"2018_SHIMMY_SE.mp4",type: 0,tags:["swingout"],desc:"",origin:"Shimmies 2018",url: "",teachers:["Sep"]},
  {id: 81,file:"lindyshock-2018/lee.mp4",type: 0,tags:[],desc:"Footwork taster",origin:"Lindy Shock 2018",teachers:["Lee"]},
  {id: 82,file:"lindyshock-2018/lsu3.mp4",type: 0,tags:[],desc:"",origin:"Lindy Shock 2018",teachers:[]},
  {id: 83,file:"lindyshock-2018/sugarpush.mp4",type: 0,tags:["sugarpush"],desc:"",origin:"Lindy Shock 2018",teachers:[]},
  {id: 84,file:"lindyshock-2018/gasalba.mp4",type: 0,tags:[],desc:"",origin:"Lindy Shock 2018",teachers:["Gas", "Alba"]},
  {id: 85,file:"shimmies-2019/separi.mp4",type: 0,tags:["swingout", "variation"],desc:"Swingout variation",origin:"Shimmies 2019",teachers:["Sep", "Ari"]},
  {id: 86,file:"IG/20200724_IG.mp4",type: 1,tags:["swingout", "texastommy", "variation"],desc:"Swingout variation",origin:"",url: "https://www.instagram.com/p/CDBAKmPB_b8/",teachers:[]},
  {id: 87,file:"shimmies-2019/greekukrain1.mp4",type: 0,tags:[],desc:"A Greek - Ukrain recipe, feb 2020",origin:"Shimmies 2019",teachers:["Alex"]},
  {id: 88,file:"shimmies-2019/greekukrain2.mp4",type: 0,tags:["6count"],desc:"A Greek - Ukrain recipe, feb 2020 - Shorten moves to 6 counts",origin:"Shimmies 2019",teachers:["Alex"]},
  {id: 89,file:"IG/2020_IG_GAAL.mp4",type: 1,tags:["lindyflip"],desc:"",origin:"",teachers:["Gaston", "Alba"]},
  {id: 90,file:"IG/20200915_IG.mp4",type: 1,tags:["charleston", "tandem"],desc:"",origin:"",url: "https://www.instagram.com/p/CFJlh9TouIT/",teachers:[]},
  {id: 91,file:"bootcamp-2021/lesson1.mp4",type: 1,tags:[],desc:"",origin:"Crazy Legs Bootcamp 2021",teachers:["Ari", "Simon"]},
  {id: 92,file:"bootcamp-2021/lesson2.mp4",type: 1,tags:[],desc:"",origin:"Crazy Legs Bootcamp 2021",teachers:["Ari", "Simon"]},
  {id: 93,file:"bootcamp-2021/lesson3.mp4",type: 1,tags:[],desc:"",origin:"Crazy Legs Bootcamp 2021",teachers:["Ari", "Simon"]},
  {id: 94,file:"bootcamp-2021/lesson4.mp4",type: 1,tags:[],desc:"",origin:"Crazy Legs Bootcamp 2021",teachers:["Ari", "Simon"]},
  {id: 95,file:"bootcamp-2021/lesson5.mp4",type: 1,tags:[],desc:"",origin:"Crazy Legs Bootcamp 2021",teachers:["Ari", "Simon"]},
  {id: 96,file:"https://drive.google.com/file/d/1GMFLyHVpfmxi85VcQ6nuvv2YpWiDwnw7dg/preview",type: 4,tags:[],desc:"",origin:"Easy steps for Happy Dancers",teachers:["Olga", "Alex Kuznetsov"]},
  {id: 97,file:"IG/274535870_678350680182191_2149657886333462657_n.mp4",type: 1,tags:["swingout"],desc:"",origin:"",url: "https://www.instagram.com/p/CaSVPPvJKlT/",teachers:["Peter", "Naomi"]},
  {id: 98,file:"youtube/ILHC 2013 Invitational Jack Jill Max Pitruzzella Sharon Davis.mp4",type: 3,tags:[],desc:"",origin:"",url: "https://www.youtube.com/watch?v=_BlXwNFwjys",teachers:["Max Pitruzella", "Sharon Davis"]},
  {id: 99,file:"burning-swing-2022/astridsloopi2.mp4",type: 0,tags:["fast"],desc:"Days at the races",origin:"Burning Swing XL",teachers:["Astrid", "Sloopi"]},
  {id: 100,file:"burning-swing-2022/alexjill.mp4",type: 0,tags:["slides"],desc:"",origin:"Burning Swing XL",teachers:["Jill", "Alexander"]},
  {id: 101,file:"burning-swing-2022/beatricesander.mp4",type: 0,tags:[],desc:"",origin:"Burning Swing XL",teachers:["Beatrice", "Sander"]},
  {id: 102,file:"nils-bianca-leuven/teachers1.mp4",type: 0,tags:[],desc:"",origin:"Nils Bianca workshop",teachers:["Nils", "Bianca"]},
  {id: 103,file:"nils-bianca-leuven/teachers2.mp4",type: 0,tags:[],desc:"",origin:"Nils Bianca workshop",teachers:["Nils", "Bianca"]},
  {id: 104,file:"nils-bianca-leuven/advanced.mp4",type: 0,tags:[],desc:"",origin:"Nils Bianca workshop",teachers:["Nils", "Bianca"]},
  {id: 105,file:"elise/313336890_1561464770974878_1170689164463394003_n.mp4",type: 0,tags:["elise"],desc:"",origin:"",url:"https://www.facebook.com/watch/?extid=WA-UNK-UNK-UNK-AN_GK0T-GK1C&v=1161940281077693",teachers:[]},
  {id: 106,file:"elise/309448797_792417745415850_6207372619951150999_n.mp4",type: 3,tags:["elise"],desc:"",origin:"",url:"https://www.instagram.com/p/CjA6Owig26m/",teachers:["Jérémy", "Mélanie"]},
  {id: 107,file:"solo-routines/TrankyDoo-Leni.mp4",type: 3,tags:["tranky doo"],desc:"Tranky Doo",origin: "",url: "",teachers:["Leni"]},
  {id: 108,file:"solo-routines/Al & Leon Shim Sham - Joris.mp4",type: 3,tags:["shim sham", "routine"],desc:"Al & Leon Shim Sham",origin: "",url: "",teachers:["Joris"]},
  {id: 109,file:"routines/joris-elle-california.mp4",type: 3,tags:["california", "routine"],desc:"California Routine",origin: "",url: "",teachers:["Joris", "Elle Brenecki"]},
  {id: 110,file:"routines/The California Routine- Spirit Moves.mp4",type: 3,tags:["california", "routine"],desc:"California Routine from The Spirit Moves",origin: "",url: "",teachers:[]},
  {id: 111,file:"solo-routines/Roulement - Joris & Simon.mp4",type: 3,tags:["roulement", "routine"],desc:"10 years Big Band Mouvement Routine",origin: "",url: "",teachers:["Joris", "Simon Lagrange"]},
  {id: 112,file:"routines/20220620_first-stops2.mp4",type: 3,tags:["first stops", "routine"],desc:"First Stops",origin: "",url: "",teachers:[]},
  {id: 113,file:"routines/bluedrag-couple.mp4",type: 3,tags:["blue drag", "couple", "routine"],desc: "Blue Drag Shag routine",origin: "",url: "",teachers:[]},
  {id: 114,file:"routines/bluedrag-solo.mp4",type: 3,tags:["blue drag", "solo", "routine"],desc: "Blue Drag Shag routine",origin: "",url: "",teachers:["Nils", "Bianca" ]},
  {id: 115,file:"youtube/RTSF 2018 Nils Bianca_1080p.mp4",type: 1,tags:[],desc: "",origin: "",url: "https://www.youtube.com/watch?v=alLi8i9BQK4",teachers:["Nils", "Bianca" ]},
  //{id: 200,file:"routines/bluedrag-solo.mp4",type: 3,tags:["blue drag", "solo", "routine"],desc: "Blue Drag Shag routine",origin: "",url: "",teachers:[]}
  {id: 116,file:"littlebigswing-2023/20230929_185324.mp4",type: 1,tags:["sugar push"],desc:"",origin:"Little Big Swing Camp 2023",teachers:["Ari", "Simon"]},
  {id: 118,file:"littlebigswing-2023/20230930_125401.mp4",type: 1,tags:[],desc:"",origin:"Little Big Swing Camp 2023",teachers:["Hector", "Sonja"]},
  {id: 119,file:"littlebigswing-2023/VID-20231001-WA0001.mp4",type: 1,tags:[],desc:"",origin:"Little Big Swing Camp 2023",teachers:["Ari", "Simon"]},
]
